apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-label
    spec:
      containers:
      - name: nginx-name
        image: nginx
        ports:
        - name: nginx-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: nginx-port
          initialDelaySeconds: 15
          timeoutSeconds: 30
