apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-label
spec:
  containers:
  - name: nginx-name
    image: nginx
    ports:
    - name: nginx-port
      containerPort: 80
