apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
  - port: 31111
    nodePort: 31111
    targetPort: nginx-port
    protocol: TCP
  selector:
    app: nginx-label
  type: NodePort
